# Generated by Django 3.2.4 on 2021-06-27 16:20

import Weblog_Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان مطلب')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to=Weblog_Blog.models.image_path, verbose_name='تصویر')),
                ('active', models.IntegerField(choices=[('0', 'غیرفعال'), ('1', 'فعال')], verbose_name='فعال/غیر فعال')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
                'ordering': ['-created_date'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
