# Generated by Django 3.2.4 on 2021-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog_Blog', '0002_alter_blogcontent_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
