# Generated by Django 3.2.4 on 2021-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog_Blog', '0004_auto_20210628_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='category',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='category',
            field=models.ManyToManyField(null=True, to='Weblog_Blog.Category', verbose_name='دسته بندی'),
        ),
    ]
