# Generated by Django 3.2.4 on 2021-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog_Blog', '0006_alter_blogcontent_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='category',
            field=models.ManyToManyField(to='Weblog_Blog.Category', verbose_name='دسته بندی'),
        ),
    ]
