# Generated by Django 3.2.4 on 2021-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog_Blog', '0009_alter_socialmedias_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات'),
        ),
    ]
