# Generated by Django 3.2.4 on 2021-06-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog_Blog', '0011_footerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerinfo',
            old_name='Address',
            new_name='address',
        ),
    ]
